on:
  workflow_call:
    inputs:
      allow-failure:
        type: boolean
        required: false
        default: false
      configuration-file:
        type: string
        required: false
        default: "renovate.json"

jobs:
  validate:
    runs-on: ubuntu-24.04
    container: ghcr.io/blindfoldedsurgery/renovate-validator:latest
    continue-on-error: ${{ inputs.allow-failure }}
    steps:
      - uses: actions/checkout@v4
      - run: renovate-config-validator --strict
        env:
          RENOVATE_CONFIG_FILE: ${{ inputs.configuration-file }}
