name: Main

on:
  push:
    branches: [ main ]
  pull_request: { }
  schedule:
    - cron: "*/12 */4 * * *"

jobs:
  validate:
    strategy:
      matrix:
        configuration-file: [ "default.json", "java.json", "pub.json", "python.json" ]
    uses: ./.github/workflows/validate.yml
    with:
      configuration-file: ${{ matrix.configuration-file }}
