name: Main

on:
  push:
    branches: [ main ]
  pull_request: { }
  schedule:
    - cron: "*/12 */4 * * *"

permissions:
  contents: read

jobs:
  build-renovate-image:
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-buildah.yml@v7
    if: github.event_name != 'schedule'
    permissions:
      contents: read
      packages: write
    with:
      image-name: renovate-validator
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}
      version: latest

  validate:
    strategy:
      matrix:
        configuration-file: [ "default.json", "java.json", "pub.json", "python.json" ]
    uses: ./.github/workflows/validate.yml
    with:
      configuration-file: ${{ matrix.configuration-file }}

  clean:
    if: false && github.ref_name == github.event.repository.default_branch
    concurrency: cleanup
    needs: build-renovate-image
    uses: BlindfoldedSurgery/actions-container/.github/workflows/clean.yml@v7
    permissions:
      packages: write
    with:
      image-name: renovate-validator
      min-versions-to-keep: 1
